services:
  - type: web
    name: my-web-service
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn myapp:app  # Replace with your app's start command
